### ISSUE TITLE
Just updated mekanism , and now this crashes on start up

### ISSUE THREAD

**Issue by crunkazcanbe** [Nividica/ThaumicEnergistics#147] opened 2015-03-20 20:33 UTC
http://pastebin.com/bNawFp06

Have not even made a world yet :/ Just crashes before I can start . What does this mod have to do with mekanism ?

Thank you!

-Crunk

**Comment by ShawnRHayes** [comment] 2015-03-20 21:34
same crash as well AE2 rv-14 , 8.9.0b-rv2 Mekanism 8

**Comment by warezit** [comment] 2015-03-20 22:22
Confirmed same crash also after upgrading to Mek8 http://pastebin.com/DCdsiy8E

'Mekanism-1.7.10-8.0.0.188'
'thaumicenergistics-0.8.9.0b-rv2'
'appliedenergistics2-rv2-beta-8'

**Comment by citpo** [comment] 2015-03-21 05:52
Same problem here when adding Mekanism 8 to FTB Infinity Pack, containing thaumicenergistics-0.8.9.0b-rv2

**Comment by crunkazcanbe** [comment] 2015-03-21 06:08
This was fixed in a dev version of mekanism . Nevermind .

**Comment by Sailren** [comment] 2015-03-21 14:31
problem is, mek devs are not available to the public

**Comment by jburrows82** [comment] 2015-03-21 14:42
I can confirm version 8.0.1.536 (latest Mek-dev) doesn't exhibit this problem. 

@Sailren Correct, only supporters are granted access to the developer versions. I would imagine 8.0.1.190 (189 failed on the jenkins) will be out today 

@Nividica I didn't check closed issues, sorry.

**Comment by Morpheus1101** [comment] 2015-03-22 09:00
So am i to understand this issue is solved, but the public have to wait for a newer vers of mekanism to be released?

**Comment by warezit** [comment] 2015-03-22 20:22
@Morpheus1101 yup, that's the way I read it also

**Comment by crunkazcanbe** [comment] 2015-03-22 20:41
Well if you like the mod donate to the mod author and you to will get access to the dev build . It's running nice to me he even threw in a option in his config to hide the portable tanks in his mod now for me since they where causing lag in the creative tab. :) i have had a dev build of version 8 way before it was even released to the public for over three months now.

**Comment by crunkazcanbe** [comment] 2015-03-22 20:42
If i was you guys play the old version 7 until he puts out a stable version for you for version 8

**Comment by luffykick** [comment] 2015-03-22 22:18
Latest version that fixes this issue was posted by aidancbrady here https://www.reddit.com/r/feedthebeast/comments/2zq6s5/mekanism_v8_is_out/

but be warned users reported this version is unstable...

the official bugfixed version should be out soon, if not already...

**Comment by Xaethon** [comment] 2015-03-22 23:49
Latest version is still crashing. Discussed it with Aidan and he said he hasn't done anything to fix it. This is with mekanism 8.0.1.196
http://pastebin.com/KrKx6uCu

**Comment by katur239** [comment] 2015-03-22 23:52
http://pastebin.com/2zBTC9Kh

Updated to latest build of Mekanism (8.0.1.196) just released and still crashes on launch.

**Comment by jburrows82** [comment] 2015-03-23 00:48
The dropbox versions work fine. It's the Mek-dev builds (5xx) that people are confusing for the public versions (1xx, soon to be 2xx) that are working fine. The latest .544 works, along with .536 worked fine for me. Haven't tested the public .197 yet, but they merged the development branch into their master branch so there is no reason why it shouldn't work.

**Comment by katur239** [comment] 2015-03-23 01:39
196 was pushed public 2 hours ago. I do not know what Dev versions were merged into that version so I do not know why it doesn't work.

**Comment by jburrows82** [comment] 2015-03-23 01:55
Dev branch is only 4 commits ahead of master with the latest changes just made. Commits yesterday up to 536 didn't indicate anything that would have resolved this problem directly -- the dev branch for whatever reason worked when .188/master would not.

You can follow the mek-dev branch @ http://github.com/aidancbrady/Mekanism/tree/development

**Comment by Nividica** [comment] 2015-03-23 16:42
One of three things is happening, the line of code that is crashing is:
AspectList cellAspects = ThaumcraftApiHelper.getObjectAspects( AEApi.instance().items().itemCell1k.stack( 1 ) ).copy();

So either the ThaumcraftApiHelper is null, something in the AEApi chain is null, or aspect registration of AE cells is failing.

None of the crash reports include the init log, so I can't say for certain which is happening.

**Comment by katur239** [comment] 2015-03-23 19:55
Here is a Init log of just AE2, TC, Thaumic Energisitics and Mekanism

http://pastebin.com/cFfpSWZd

**Comment by anishin** [comment] 2015-03-24 08:01
I have the same problem with Thaumic Energistics and Mekanism (8.0.1.196). As I understand, problem is in Mekanism AND AE2. (AE2 stores old Mekanism API, that is incompatitible with Mek8API.)
So all recipes from AE2 and AE2 addons don't works (see AE2 Issue tracker).

P. S. Sorry for my English. I'm from Russia.

**Comment by ChatFawkes** [comment] 2015-03-24 22:55
Well Mekanism 8.0.2.200 was just pushed and after trying it I can confirm the issue still happens.

[Crash Report](https://gist.github.com/ChatFawkes/4c15296421e3912a7fc8)

**Comment by crunkazcanbe** [comment] 2015-03-25 00:34
I reported this for you guys over at https://github.com/aidancbrady/Mekanism/issues/2358

**Comment by lehjr** [comment] 2015-03-25 17:10
"Well Nevermind guys its a AE2 issue"

Specifically, looks like AE2 is using an outdated Mekanism API. I did a test build of AE2 using the API for Mekanism 1.7.10-8.0.1.198 and the game loads fine. 

Note this requires a small edit in AE2: /src/main//java/appeng/integration/modules/Mekanism.java
from: 
import mekanism.api.RecipeHelper;
to:
import mekanism.api.recipe.RecipeHelper;

So users can either wait for an update to come from AE devs or disable Mekanism integration in the AE2 config file.

**Comment by Morpheus1101** [comment] 2015-03-26 09:44
The problem is the diff mod's are blaming the other mod's for the problem and nothing is being done to actually fix it.

**Comment by katur239** [comment] 2015-03-27 01:30
I would like to add that with AE2 rv 18, Mekanism 8.0.2.201 everything works as intended ;D

**Comment by crunkazcanbe** [comment] 2015-03-27 04:58
Yep it does :)

**Closed** 2015-03-27 22:52 UTC
