### ISSUE TITLE
Void-Aspected Primal Staff and the Arcane Crafting Terminal

### ISSUE THREAD

**Issue by Arcandustrialist** [Nividica/ThaumicEnergistics#188] opened 2015-05-22 14:05 UTC
I was trying to use the Arcane Crafting Terminal to make a staff from void metal caps and a primal staff core.

I had a fully-charged ichorium wand in the terminal, so vis was not an issue.

When I attempted to pull the completed staff out of the crafting result box, the item would be pulled just a tiny bit, then snap back into the result box.

Putting the materials and the wand in a normal TC arcane workbench allowed me to craft the staff without a problem.

**Comment by Nividica** [comment] 2015-05-23 04:37
Thank you for this report. As it turns out it was a sync issue, but not in the direction you would expect, as it was the server side that was out of sync.
Steps to reproduce:
* ACT must be linked to an active VRI
* There must be a wand without full charge in the ACT.
* Set a crafting recipe that requires more vis than the wand has.
* Wait for the wand to have enough vis, do not close GUI, and attempt to pull out the crafting result.
* Item will snap back

The problem was that as the wand charged, the update packets being sent that was causing the client to re-evaluate the crafting. However I was not informing the server-side half that the wand charge had changed, so it was not re-evaluating the crafting. As such the client would know that there was something ready to be crafted, but the server was still under the impression there was not enough vis.

This will be fixed in the 0.8.10.3 release. However for now if you run into this issue again, you can either leave and re-open the gui, or remove and replace a crafting ingredient and it will update.

**Closed** 2015-05-23 04:38 UTC
