### ISSUE TITLE
Server Crash: Place Arcane Assembler Next To Multiple ME Crafting Multiblocks

### ISSUE THREAD

**Issue by Anarcraft** [Nividica/ThaumicEnergistics#133] opened 2015-02-14 02:07 UTC
Crash upon placement of the assembler next to multiple ME crafting multiblocks (Crafting Storage/Co-Processing Units).  Doesn't occur if only next to a single crafting multiblock.

appliedenergistics2-rv2-beta-8, Thaumcraft-1.7.10-4.2.3.4, forge10.13.2.1291.

http://pastebin.com/jY1YEgke

**Comment by Nividica** [comment] 2015-02-27 20:29
Apologies for not getting back sooner.
From just looking at the crash log it looks like something is trying to make two connections to the network. I will need to do some testing to track down the root cause as I am not sure what could possible be different about connecting it to a multiblock crafter as apposed to any other network block.

I'm moving this to the top of the ToDo list and will explore it soon as I get the time. Thanks for letting me know.

**Comment by Anarcraft** [comment] 2015-03-09 02:56
I don't know if it has anything to do with a multiblock or not, it's just what happens to be next to my assemblers and I didn't test it with other network blocks.

**Closed** 2015-03-31 20:37 UTC
Labels: bug
