### ISSUE TITLE
Essentia Export Bus crash when connected to Thaumatorium

### ISSUE THREAD

**Issue by Gepett0** [Nividica/ThaumicEnergistics#361] opened 2019-01-02 15:14 UTC
Hi,

couldn't find any thread newer than March 2018.
Our server keeps crashing on load.
MC 1.12.2
TE: 2.0.0
AE: rv6-stable-4

It's Sky Adventures with some bonus mods (TE, Equivalent Exchange)

Pastebin Crash Report: https://pastebin.com/fEDV3LKe

Tried loading in SP but also crashes.

BR

**Comment by BrockWS** [comment] 2019-01-02 16:14
Looks like an issue with Thaumcraft, trying to add Essentia while there is no recipe selected looks to be the cause. Looks like its supposed to check for a recipe but the code placement is wrong. If you could, please post an issue [here](https://github.com/Azanor/thaumcraft-beta/issues) and link back to this one.

**Comment by BrockWS** [comment] 2019-01-05 12:17
Going to close this since its a Thaumcraft bug, but I've added a small fix to prevent the crash since it might be awhile until a tc update is out.

**Closed by BrockWS** 2019-01-05 12:17 UTC
Labels: bug
