### ISSUE TITLE
Level emitter update bug

### ISSUE THREAD

**Issue by AltonV** [Nividica/ThaumicEnergistics#209] opened 2015-07-02 21:17 UTC
When using the essentia level emitter the status of redstone/red alloy wire only gets updated if a block update occurs next to it.

**Comment by Nividica** [comment] 2015-07-03 00:18
When the emitter changes state it issues a block update itself. Testing redstone dust shows that it properly changes state when the emitter does, however I have not tested any other redstone transmission mediums.
![emitterredstone](https://cloud.githubusercontent.com/assets/1585989/8490463/56f5de4e-20f7-11e5-9f10-237283a6c284.jpg)

**Comment by AltonV** [comment] 2015-07-03 05:57
If I place the emitter at the same level as the redstone it does not work at all
![2015-07-03_07 42 58](https://cloud.githubusercontent.com/assets/193494/8493238/bea27330-2157-11e5-8cd1-7719cc516b3a.png)
![2015-07-03_07 48 01](https://cloud.githubusercontent.com/assets/193494/8493271/2b5c4d34-2158-11e5-8c5a-2432554f0bf7.png)


But if I place it at the level as the block below the redstone it works when a block update occurs.
![2015-07-03_07 44 06](https://cloud.githubusercontent.com/assets/193494/8493244/e7a282de-2157-11e5-82d3-8961009be79a.png)
![2015-07-03_07 44 23](https://cloud.githubusercontent.com/assets/193494/8493248/edba3e3c-2157-11e5-8fb9-5d63edddb83f.png)

It is the same behavior with red alloy wire from project red.

Forge version: 10.13.4.1448
Thaumic Energistics version: 0.8.10.5
Applied Energistics 2 version: rv2-stable-9

**Comment by Nividica** [comment] 2015-07-03 06:57
When you get a chance, see if 0.8.10.6 fixes the issue for you.
http://minecraft.curseforge.com/mc-mods/223666-thaumic-energistics/files/2245337

**Comment by AltonV** [comment] 2015-07-03 14:56
No change :(

**Comment by Nividica** [comment] 2015-07-04 04:29
Interesting, I am at a loss as to why I can not reproduce this issue. A few questions that could help me narrow down the issue:
* Does the issue occur with the AE level emitter?
* If you go inside the GUI and change the redstone mode manually back and forth, does it update the adjacent redstone?
* Does the issue occur in a new world?
* Does the emitter show particles when active? (Assuming you have particles enabled)

**Comment by AltonV** [comment] 2015-07-04 13:28
1: No
2: No (yes in new world)
3: No
4: No (yes in new world)

**Comment by AltonV** [comment] 2015-07-04 13:43
It seems it is an issue with the placement of the emitter.
Both emitters in the pictures have the same settings and connected to the same network.

![2015-07-04_15 37 06](https://cloud.githubusercontent.com/assets/193494/8508096/ca812b4a-2262-11e5-8794-9031bfb791c9.png)

![2015-07-04_15 36 52](https://cloud.githubusercontent.com/assets/193494/8508099/eb0274fa-2262-11e5-856f-038a53e659ea.png)

![2015-07-04_15 37 03](https://cloud.githubusercontent.com/assets/193494/8508101/faafae2c-2262-11e5-9c21-630915f0b06d.png)

**Comment by Nividica** [comment] 2015-07-04 19:40
I've updated the level emitter code, try out this build and see if it corrects the issue.
https://drive.google.com/file/d/0B3XsROkASZNETTdQaGdES0dtams/view?usp=sharing

**Comment by AltonV** [comment] 2015-07-04 20:32
Still some issues.
Same settings on all emitters
The two emitters furthest away worked immediately and the middle was grey (like not connected to a network grey) until I toggled the redstone mode back and forth several times.
Last two didn't work at all
![2015-07-04_22 18 12](https://cloud.githubusercontent.com/assets/193494/8509273/dc59cc04-229a-11e5-8a8c-8a91ed89eafc.png)


Placing an emitter after those worked.
And in the background you can see more working emitters
![2015-07-04_22 28 55](https://cloud.githubusercontent.com/assets/193494/8509290/2f50478e-229c-11e5-8d12-f9b1ad78483a.png)

**Comment by Nividica** [comment] 2015-07-04 21:11
I am including some debug code in the build, you can shift+rightclick on each emitter to get some stats about it:
* Threshold Amount: Amount set in GUI
* Network Amount: Amount emitter see's in network
* Mode: Emit if >= or <
* Emitting: Yes or No
* Connected: Yes or No

Compare one that is working as expected vs. one that is not. If they perfectly match then unfortunately I am out of ideas. If they do not match, there may be sync issue. Either way let me know at your earliest convenience.

https://drive.google.com/file/d/0B3XsROkASZNELUtlZzVRVXRsTFU/view?usp=sharing

**Comment by AltonV** [comment] 2015-07-04 21:26
Working emitter amount: 997
Non-working emitter amount: 0

![2015-07-04_23 22 43](https://cloud.githubusercontent.com/assets/193494/8509445/ab748508-22a3-11e5-9d53-15ddfd6e40ca.png)

**Comment by Nividica** [comment] 2015-07-04 22:05
There is definitely a sync issue at play. This build includes some potential fixes and should give me all the info I need to track down where the issue is occurring if it is not fixed. I apologize for taking up your time having you test these builds for me.
The debug info now includes what aspect is being tracked, what stage of monitoring has been completed, and the ID of the monitor.
For the stages:
1: No aspect is set
2: Unable to access essentia monitor system
3: Everything should be working, monitor ID is set.

The monitor ID should be the same for every emitter on the same network.

https://drive.google.com/file/d/0B3XsROkASZNEbm1YM250TlNzSG8/view?usp=sharing

**Comment by AltonV** [comment] 2015-07-05 09:13
Picture shows output from a working emitter and a non-working.
After replacing a faulty emitter it shows the correct amount but still does not output a signal.
![2015-07-05_11 04 27](https://cloud.githubusercontent.com/assets/193494/8511041/c194a02c-2305-11e5-8185-cb05f5961a97.png)

**Comment by Xiaminou** [comment] 2015-07-05 14:27
Can I just use this thread to say that button on the essentia level emitters are reversed? in Applied Energistics the buttons to increase ("+1", "+10" etc...) are on the top and the buttons to decreases are on the bottom.

**Comment by Nividica** [comment] 2015-07-25 22:17
With the new network changes fully in-place in 0.8.10.8, are you, or anyone else, still having issues with the level emitters?

**Comment by Nividica** [comment] 2015-08-18 19:26
No additional feedback provided. Closing issue.

**Closed by Nividica** 2015-08-18 19:26 UTC
Labels: bug, Need More Information
