### ISSUE TITLE
Crash on startup with AE2-RV2-Beta 21

### ISSUE THREAD

**Issue by lehjr** [Nividica/ThaumicEnergistics#155] opened 2015-03-28 19:27 UTC
Hope you're ready for the next round of changes:
http://pastebin.com/ciZC16k8
Edit: this is with thaumicenergistics-0.8.9.0b-rv2

**Comment by Dream-Master** [comment] 2015-03-28 22:26
I get the same error.

**Comment by ShawnRHayes** [comment] 2015-03-29 00:03
this might help 

Caused by: java.lang.InstantiationError: appeng.parts.automation.UpgradeInventory
	at thaumicenergistics.tileentities.TileArcaneAssembler.<init>(TileArcaneAssembler.java:227)
	at thaumicenergistics.registries.Renderers.registerRenderers(Renderers.java:59)
	at thaumicenergistics.proxy.ClientProxy.registerRenderers(ClientProxy.java:21)
	at thaumicenergistics.ThaumicEnergistics.load(ThaumicEnergistics.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)

**Comment by lehjr** [comment] 2015-03-29 01:24
In the source, UpgradeInventory becomes StackUpgradeInventory, but then there's this compile fail:

/home/leon/development/ThaumicEnergistics/src/main/java/thaumicenergistics/inventory/HandlerEssentiaStorageBusInterface.java
Error:(238, 45) java: myAccess has private access in appeng.me.storage.MEInventoryHandler
Error:(239, 45) java: myWhitelist has private access in appeng.me.storage.MEInventoryHandler
Error:(240, 45) java: myPriority has private access in appeng.me.storage.MEInventoryHandler

And then there's a ton of depreciation warnings. Good luck.

**Comment by katur239** [comment] 2015-03-29 01:25
Here is the full Launch log . AE2 Rv2 Beta 21

http://pastebin.com/Nyt4PmGj

**Comment by oks1998** [comment] 2015-03-29 10:55
my minecraft just crash when run, the crash report didn't generate yet

**Comment by abdullamu** [comment] 2015-03-29 11:52
same error here

**Comment by katur239** [comment] 2015-03-29 12:55
Here is another oddity; Seems to only crash clients. I put beta 21 on my server and it launches just fine.

**Comment by lehjr** [comment] 2015-03-29 13:18
There are some problems with AE2 RV2 19+ atm see:https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1118#issuecomment-87303949. So it's likely any Thaumic Energistics fix will have to wait until AE2 issues are fixed.

**Comment by crunkazcanbe** [comment] 2015-03-30 21:54
I was coming here to post this too .

**Comment by usafphoenix** [comment] 2015-03-31 05:52
getting this error with AE2 RV2 20,21,22. (reverted back to build 14 and worked fine) eventually disabled all other mods and tried AE2 with each of the mods which adds to it and isolated it to a new incompatibility between thaumic energistics and AE2. yay

**Comment by Nividica** [comment] 2015-03-31 20:14
Given the stability issues with with 19+ I am not going to focus on updating to support it until I get the current bugs worked out for 18. However if I can manage to get those taken care of today, I will post an alpha build for the the latest AE2. Just be aware that I won't be offering a good deal, if any, support for it just yet.

**Comment by lehjr** [comment] 2015-03-31 20:33
Latest AE2 source works better than the latest build

**Comment by Sailren** [comment] 2015-03-31 20:58
same error here, but thx that nvidica and thatsIch is working on it

**Comment by Iomega0318** [comment] 2015-04-02 01:39
I was just coming here to report this, I am using:

thaumicenergistics-0.8.9.1b-rv2
- and -
 appliedenergistics2-rv2-beta-22

Still getting the same crash, and @katur239 yes odd behavior only crashes the client not the server. I would love a fix for this even it it's a hack for now as I can't live without either mod, however AE b22 fixes an error that I have been needing fixed since AE2 came out :(

**Comment by lehjr** [comment] 2015-04-02 02:06
Thaumic Energistics hasn't been updated for AE2 beta 22 yet. Beta 22 still has issues. 18+ is like windows updates, fix 1 thing and break 20 others (I can't even load an existing map with it without it crashing). I think Nividica is waiting for a reliable AE2 build before updating.

**Comment by marduvGitHub** [comment] 2015-04-02 02:08
I also have the same issue as you @Iomega0318 :-(

I'm using the latest versions available:
thaumicenergistics-0.8.9.1b-rv2
appliedenergistics2-rv2-beta-22

**Comment by Iomega0318** [comment] 2015-04-02 02:16
@lehjr AE b22 works fine for me, and like I said I "have" to use it. It fixes a bug that I have needed fixed in order to run it on my server, up until now I have been running the server off my desktop computer. (weird bug don't ask.. no idea)

@marduvGitHub yep sad times, I may end up removing TE until it works with AE b22+ :(

**Comment by Nividica** [comment] 2015-04-02 23:06
I will attempt to get a working alpha build for 22 posted tonight.

**Comment by Iomega0318** [comment] 2015-04-02 23:11
That would be amazing! and even if it's a hack temp fix for now just so I can use it lol, I'd love you forever :)

**Comment by Nividica** [comment] 2015-04-02 23:38
There is an amazing amount of changes to the AEApi, as such I won't be able to reliably test it tonight, but if I can at least get it operational I will release an alpha.

**Comment by Iomega0318** [comment] 2015-04-02 23:41
No worries, as long as I can start the server without deleting things I'll be happy :)

**Comment by Nividica** [comment] 2015-04-03 01:18
[0.8.9.2a-rv2](http://minecraft.curseforge.com/mc-mods/223666-thaumic-energistics/files/2232574) is posted.

**Comment by warezit** [comment] 2015-04-03 15:25
Confirmed working with:
AE 2 rev2 beta 22
TE 0.8.9.2a-rv2

**Comment by yueh** [comment] 2015-04-03 17:15
Just to get some things straight.
There was absolutely no breaking change to the API. Only some things marked as `@Deprecated`, which means they will be removed at some point in the future. But probably not before rv4, maybe rv3 (low chance).

Regarding your changes.
You can expect that calling `Optional.get()` will crash without checking `Optional.isPresent()` before or using more appropriate methods.

Also mostly as heads-up.
Anything which is not part of the API is always subject to change and will break without warning. This basically includes anything outside the `appeng.api` package.
It is very likely that we start moving around packages in the near future. So expect any build to potentially break things except the API.

**Comment by Nividica** [comment] 2015-04-03 19:39
Ah, the .isPresent() was something I did miss.
And most of the difficulty with the API update came from the aspect registry where I an having to do a lot of reflection and chaining of recipes to build the full list of ingredients and assigning aspects based off of those.
Outside of aspect registry the rest of the changes were quite minor, but occurred all over the place in my code. I suppose I could have left the depricated calls intact, but by default I have eclipse set up to funnel all warnings into errors. As such when I opened the project with 22, I was informed of over 400 errors. @_@
Overall I like the changes, esp the .orNull(), as it simplified my code in a few key spots.

**Comment by Iomega0318** [comment] 2015-04-03 22:12
@Nividica Awesome, thank you!

Confirmed working with:
appliedenergistics2-rv2-beta-23
thaumicenergistics-0.8.9.2a-rv2

**Comment by yueh** [comment] 2015-04-03 22:37
If you want to execute something when an item/block exists, then you should maybe look at `Optional.asSet()` and use it with a foreach. If it is present, it will run once else never. For example anywhere you are using `.orNull()` and then `if(!null)`.

An easy way to really break it is disabling every feature via the ae2.cfg. If you survive this without any exception, you can pretty much assume it works always.

**Comment by Nividica** [comment] 2015-04-03 22:50
@yueh That has to be the best idea that I have heard yet for compatibility testing. I tend to make the assumption that nothing has been disabled and work back from there. Working forward assuming everything is disabled seems like a much better way to approach finding my issues.

**Closed** 2015-04-08 11:43 UTC
Labels: bug
